name: 'upi_payments'
version: '1.0.0'
config-version: 2

profile: 'upi_payments'

model-paths: ["models"]
test-paths: ["tests"]
seed-paths: ["seeds"]
macro-paths: ["macros"]

target-path: "target"
clean-targets:
  - "target"
  - "dbt_packages"

models:
  upi_payments:
    staging:
      +materialized: view
      +schema: staging
    intermediate:
      +materialized: view
      +schema: intermediate
    marts:
      +materialized: table
      +schema: marts
      fact_transactions:
        +materialized: incremental

packages:
  - package: dbt-labs/dbt_utils
    version: [">=1.0.0", "<2.0.0"]